# Generated by Django 4.2.1 on 2023-06-04 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpostdb',
            name='body',
        ),
        migrations.AddField(
            model_name='blogpostdb',
            name='blog_image',
            field=models.ImageField(blank=True, null=True, upload_to='Post-Images'),
        ),
        migrations.AddField(
            model_name='blogpostdb',
            name='caption',
            field=models.TextField(blank=True),
        ),
    ]
