# Generated by Django 4.2.1 on 2023-06-07 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_remove_blogpostdb_body_blogpostdb_blog_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpostdb',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.userprofiledb'),
        ),
    ]
