# Generated by Django 4.2.1 on 2023-06-12 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_blogpostdb_author_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofiledb',
            name='profil_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
